name: CI workflow

on: 
    push:
        branches:
            - build

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2 # CHECK VERSION

            - name: Setup Node.js version 18.17.1
              uses: actions/setup-node@v1
              with:
                node-version: '18.17.1'

            - name: Remove node_modules
              run: rm -rf node_modules

            - name: Install dependencies
              run: npm install
            
            - name: Authorize Github Token
              run: export GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}

            - name: Run tests
              run: ./run test
    
    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build

    #     steps:
    #         - uses: actions/checkout@v2

    #         - name: Configure AWS Credentials
    #           uses: aws-actions/configure-aws-credentials@v2  # CHECK THIS SECTION
    #           with:
    #             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #             aws-region: us-east-1
            
            
            # - name: Deploy to Lambda
            #   run: |

            # - name: Deploy to S3
            #   run: |
            
            # - name: EC2 Deployment
            #   run: |
            
            # - name: CodeBuilder
            #     run: |
        

                
                